@startuml sistemaCalificia

' Definimos los actores principales

Class Cliente {
    - id: int
    - correo: String
    - nombre: String
    - pass: String
    - tipoCuenta: int
    + generarExamen(contenido: Documento, nivel: Documento, objetivos: List<String>): Examen
    + revisarResultados(examen: Examen): void
    + presentarExamen(examen: Examen): Resultado
}

Class Auth {
    + verificarAuten(): bool
    + verificarAutor(): bool
    + login(correo, pass, tipoCuenta: Cliente): bool
    + logout(): String
}

class Profesor {
}

class Estudiante {
}

class Examen {
    - id: int
    - fechaCreacion: Date
    - nivelEducativo: String
    - objetivos: List<String>
    - preguntas: List<Pregunta>
    + agregarPregunta(p: Pregunta): void
}

class Pregunta {
    - id: int
    - texto: String
    - opciones: List<String>
    - respuestaCorrecta: String
    + evaluar(respuestaEstudiante: String): bool
}

class Documento {
    - id: int
    - tipo: String <<PDF, DOCX>>
    - contenido: String
    + analizarContenido(): List<String>
}

class IA {
    + generarPreguntas(documento: Documento, objetivos: Examen): List<Pregunta>
    + evaluarExamen(examen: Examen, respuestas: Map<int, String>): Resultado
}

class Resultado {
    - id: int
    - examen: Examen
    - estudiante: Estudiante
    - calificacion: float
    + calcularPromedio(): float
}

class GestorCalificaciones {
    + obtenerPromedio(nombre: Estudiante): float
    + mostrarEstadisticas(): void
}





' Relaciones
Cliente --> Profesor : puede ser
Cliente --> Estudiante : puede ser
Auth --> Cliente : verifica
Profesor --> Examen : crea
Estudiante --> Resultado : obtiene
Examen --> Pregunta : contiene
Examen --> Documento : usa
Examen --> IA : usa para generar
Examen --> Resultado : tiene un
GestorCalificaciones --> Resultado : gestiona
IA --> Documento : analiza
Estudiante --> Examen : hace

@enduml

